INSERT INTO movie (title, box_office, duration, description,
                   release_year, image)
VALUES ('Forrest Gump', 677387716, 144,
        'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
        1994,
        'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg'),
       ('Shawshank Redemption', 59841469,
        144,
        'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.',
        1994,
        'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg'),
       ('The Green Mile', 286801374, 168,
        'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
        1999,
        'https://m.media-amazon.com/images/M/MV5BMTA0OTU2Y2QtNjY2Yy00M2Q5LWFiYzQtODlmN2ZkOWQxNGE4XkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg'),
       ('Catch Me If You Can',
        352114312, 141,
        'Barely 21 yet, Frank is a skilled forger who has passed as a doctor, lawyer and pilot. FBI agent Carl becomes obsessed with tracking down the con man, who only revels in the pursuit.',
        2002,
        'https://m.media-amazon.com/images/M/MV5BMTY5MzYzNjc5NV5BMl5BanBnXkFtZTYwNTUyNTc2._V1_UY1200_CR89,0,630,1200_AL_.jpg'),
       ('Shutter Island', 294804195, 138,
        'In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.',
        2010,
        'https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg'),
       ('Untouchable', 426588510, 172,
        'After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.',
        2011, 'https://m.media-amazon.com/images/M/MV5BODY0MDM1MDE2OV5BMl5BanBnXkFtZTcwMzEyMjkyNw@@._V1_.jpg'),
       ('Seven', 327333559, 127,
        'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
        1995,
        'https://m.media-amazon.com/images/M/MV5BZDgyZmY5MmItY2I3Ny00NjA4LWFhNmItMGQ4ZGJhZDk5YjU3XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg'),
       ('The Sixth Sense', 672806292, 167,
        'A frightened, withdrawn Philadelphia boy who communicates with spirits seeks the help of a disheartened child psychologist.',
        1999,
        'https://m.media-amazon.com/images/M/MV5BZDRkMzc3MzQtZmI2ZS00YjVjLTk0MDQtYWY1ZDY2MDkwYTk3XkEyXkFqcGdeQXVyMjgyNDU4MjE@._V1_.jpg'),
       ('GoodFellas', 2108766, 146,
        'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
        1990,
        'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
       ('The Godfather', 245066411, 175,
        'The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.',
        1972,
        'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg'),
       ('The Godfather Part II', 193000000,
        200,
        'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
        1974,
        'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_.jpg'),
       ('Scent of a Woman', 134095253, 157,
        'A prep school student needing money agrees to "babysit" a blind man, but the job is not at all what he anticipated.',
        1992,
        'https://m.media-amazon.com/images/M/MV5BZTM3ZjA3NTctZThkYy00ODYyLTk2ZjItZmE0MmZlMTk3YjQwXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg'),
       ('Schindler ''s List', 322139355, 195,
        'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
        1993,
        'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_FMjpg_UX1000_.jpg'),
       ('What''s Eating Gilbert Grape', 287595253,
        108,
        'A young man in a small Midwestern town struggles to care for his mentally-disabled younger brother and morbidly obese mother while attempting to pursue his own happiness.',
        1993,
        'https://m.media-amazon.com/images/M/MV5BMjU5NDllOTgtMjkzYy00ZWNmLThkMTItMzU0NzMxOTM2OWY2XkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg'),
       ('Cast Away', 429632142,
        143,
        'A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.',
        2000,
        'https://m.media-amazon.com/images/M/MV5BN2Y5ZTU4YjctMDRmMC00MTg4LWE1M2MtMjk4MzVmOTE4YjkzXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_FMjpg_UX1000_.jpg'),
       ('A Beautiful Mind', 313542341, 135,
        'After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.',
        2001,
        'https://m.media-amazon.com/images/M/MV5BMzcwYWFkYzktZjAzNC00OGY1LWI4YTgtNzc5MzVjMDVmNjY0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg');

INSERT INTO actor (first_name, last_name, height, description,
                   born_year, born_place, image)
VALUES ('Tom', 'Hanks', 183,
        'Thomas Jeffrey Hanks was born in Concord, California, to Janet Marylyn (Frager), a hospital worker, and Amos Mefford Hanks, an itinerant cook.',
        1956,
        'Concord, California, USA',
        'https://m.media-amazon.com/images/M/MV5BMTQ2MjMwNDA3Nl5BMl5BanBnXkFtZTcwMTA2NDY3NQ@@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Morgan', 'Freeman', 189,
        'With an authoritative voice and calm demeanor, this ever popular American actor has grown into one of the most respected figures in modern US cinema.',
        1937, 'Memphis, Tennessee, USA',
        'https://m.media-amazon.com/images/M/MV5BMTc0MDMyMzI2OF5BMl5BanBnXkFtZTcwMzM2OTk1MQ@@._V1_.jpg'
        ),
       ('Anthony', 'Hopkins', 174,
        'Anthony Hopkins was born on December 31, 1937, in Margam, Wales, to Muriel Anne (Yeats) and Richard Arthur Hopkins, a baker.',
        1937,
        'Port Talbot, Wales, GB',
        'https://m.media-amazon.com/images/M/MV5BMTg5ODk1NTc5Ml5BMl5BanBnXkFtZTYwMjAwOTI4._V1_FMjpg_UX1000_.jpg'
        ),
       ('Joaquin', 'Phoenix', 173,
        'Joaquin Phoenix was born Joaquin Rafael Bottom in San Juan, Puerto Rico, to Arlyn (Dunetz) and John Bottom, and is the middle child in a brood of five.',
        1974,
        'San Juan, Puerto Rico',
        'https://m.media-amazon.com/images/M/MV5BZGMyY2Q4NTEtMWVkZS00NzcwLTkzNmQtYzBlMWZhZGNhMDhkXkEyXkFqcGdeQXVyNjk1MjYyNTA@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Jack', 'Nicholson', 177,
        'Jack Nicholson, an American actor, producer, director and screenwriter, is a three-time Academy Award winner and twelve-time nominee.',
        1937,
        'Neptune, New Jersey, USA',
        'https://m.media-amazon.com/images/M/MV5BMTQ3OTY0ODk0M15BMl5BanBnXkFtZTYwNzE4Njc4._V1_FMjpg_UX1000_.jpg'
        ),
       ('Robert', 'Downey Jr.', 175,
        'Robert Downey Jr. has evolved into one of the most respected actors in Hollywood.',
        1965,
        'New York, New York, USA',
        'https://m.media-amazon.com/images/M/MV5BNzg1MTUyNDYxOF5BMl5BanBnXkFtZTgwNTQ4MTE2MjE@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Alan', 'Rickman', 185,
        'Alan Rickman was born on a council estate in Acton, West London, to Margaret Doreen Rose (Bartlett), of English and Welsh descent, and Bernard Rickman, of Irish descent, who worked at a factory. ',
        1946,
        'London, England, GB',
        'https://m.media-amazon.com/images/M/MV5BMTUwNTc4MTg4Ml5BMl5BanBnXkFtZTcwNDY2MjkxOA@@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Al', 'Pacino', 170,
        'Alfredo James "Al" ''Pacino established himself as a film actor during one of cinema''s most vibrant decades, the 1970s, and has become an enduring and iconic figure in the world of American movies.',
        1940,
        'New York, New York, USA',
        'https://m.media-amazon.com/images/M/MV5BMTQzMzg1ODAyNl5BMl5BanBnXkFtZTYwMjAxODQ1._V1_.jpg'
        ),
       ('Clint', 'Eastwood', 193,
        'Clint Eastwood was born May 31, 1930 in San Francisco, the son of Clinton Eastwood Sr., a bond salesman and later manufacturing executive for Georgia-Pacific Corporation, and Ruth Wood (née Margret Ruth Runner), a housewife turned IBM clerk.',
        1930,
        'San Francisco, California, USA',
        'https://m.media-amazon.com/images/M/MV5BMTg3MDc0MjY0OV5BMl5BanBnXkFtZTcwNzU1MDAxOA@@._V1_.jpg'
        ),
       ('Benedict', 'Cumberbatch', 183,
        'Benedict Timothy Carlton Cumberbatch was born and raised in London, England. His parents, Wanda Ventham and Timothy Carlton (born Timothy Carlton Congdon Cumberbatch), are both actors.',
        1976,
        'London, England, GB',
        'https://m.media-amazon.com/images/M/MV5BMjE0MDkzMDQwOF5BMl5BanBnXkFtZTgwOTE1Mjg1MzE@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Bryan', 'Cranston', 179,
        'Bryan Lee Cranston was born on March 7, 1956 in Hollywood, California, to Audrey Peggy Sell, a radio actress, and Joe Cranston, an actor and former amateur boxer.',
        1956,
        'California, USA',
        'https://m.media-amazon.com/images/M/MV5BMTA2NjEyMTY4MTVeQTJeQWpwZ15BbWU3MDQ5NDAzNDc@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Kevin', 'Spacey', 179,
        'Kevin Spacey Fowler, better known by his stage name Kevin Spacey, is an American actor of screen and stage, film director, producer, screenwriter and singer.',
        1959,
        'South Orange, New Jersey, USA',
        'https://m.media-amazon.com/images/M/MV5BMTY1NzMyODc3Nl5BMl5BanBnXkFtZTgwNzE2MzA1NDM@._V1_.jpg'
        ),
       ('Rami', 'Malek', 175,
        'Rami Said Malek (born May 12, 1981) is an American actor.',
        1981,
        'Los Angeles, California, USA',
        'https://m.media-amazon.com/images/M/MV5BODA3OTM4ODU0MV5BMl5BanBnXkFtZTgwNjQ5Njg3NjM@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Joe', 'Pesci', 163,
        'Compact Italian-American actor Joe Pesci was born February 9, 1943 in Newark, New Jersey, to Mary (Mesce), a part-time barber, and Angelo Pesci, a bartender and forklift driver.',
        1943,
        'Newark, New Jersey, USA',
        'https://m.media-amazon.com/images/M/MV5BMzc3MTcxNDYxNV5BMl5BanBnXkFtZTcwOTI3NjE1Mw@@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Ian', 'McKellen', 180,
        'Widely regarded as one of greatest stage and screen actors both in his native Great Britain and internationally, twice nominated for the Oscar and recipient of every major theatrical award in the UK and US, Ian Murray McKellen was born on May 25, 1939 in Burnley, Lancashire, England, to Margery Lois (Sutcliffe) and Denis Murray McKellen, a civil engineer and lay preacher.',
        1939,
        'Burnley, England, GB',
        'https://m.media-amazon.com/images/M/MV5BMTQ2MjgyNjk3MV5BMl5BanBnXkFtZTcwNTA3NTY5Mg@@._V1_FMjpg_UX1000_.jpg'
        ),
       ('Christoph', 'Waltz', 174,
        'Christoph Waltz is an Austrian-German actor.',
        1956,
        'Vienna, Austria',
        'https://m.media-amazon.com/images/M/MV5BMTM4MDk3OTYxOF5BMl5BanBnXkFtZTcwMDk5OTUwOQ@@._V1_FMjpg_UX1000_.jpg'
        )
--ON CONFLICT (id)
--DO NOTHING;