version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: filmweb_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=filmweb
    #    volumes:
    #      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - '5432:5432'
