# Generated by Django 4.1.5 on 2023-01-06 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('born_place', models.CharField(max_length=50)),
                ('born_year', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('box_office', models.FloatField()),
                ('duration', models.IntegerField()),
                ('release_year', models.IntegerField()),
                ('actors', models.ManyToManyField(to='movies.actor')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
