# Generated by Django 4.1.5 on 2023-02-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.CharField(default="", max_length=500),
        ),
    ]
