# Generated by Django 4.1.5 on 2023-03-19 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_actors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.RemoveField(
            model_name='actor',
            name='born_place',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='born_year',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='height',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.AddField(
            model_name='actor',
            name='biography',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='actor',
            name='imdb_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='place_of_birth',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='actor',
            name='poster_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='adult',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='backdrop_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='box_office',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre'),
        ),
    ]
