# Generated by Django 4.1.5 on 2023-06-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0020_rename_imdb_id_actor_imdb_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="movie",
            name="imdb_path",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
