# Generated by Django 4.1.5 on 2023-07-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0023_remove_movie_id_movie_movie_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="movie_id",
        ),
        migrations.AddField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
