# Generated by Django 4.1.5 on 2023-07-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0024_remove_movie_movie_id_movie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
