# Generated by Django 4.1.5 on 2023-08-01 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0026_moviegenre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moviegenre",
            old_name="genre_id",
            new_name="genre",
        ),
        migrations.RenameField(
            model_name="moviegenre",
            old_name="movie_id",
            new_name="movie",
        ),
    ]
