# Generated by Django 4.1.5 on 2024-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0027_rename_genre_id_moviegenre_genre_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="moviegenre",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(default=0),
        ),
    ]
