# Generated by Django 4.1.5 on 2024-02-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0028_alter_moviegenre_unique_together_movie_tmdb_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="tmdb_id",
            field=models.IntegerField(),
        ),
    ]
